# Generated by Django 2.2.2 on 2019-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
                ('del_flag', models.BooleanField(default=False, verbose_name='删除')),
                ('name', models.CharField(max_length=300, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=100, verbose_name='公司简称')),
            ],
            options={
                'verbose_name': '客户管理',
                'verbose_name_plural': '客户管理',
            },
        ),
    ]
