# Generated by Django 2.2.2 on 2019-06-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190617_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
