# Generated by Django 2.2.2 on 2019-06-17 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190617_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='del_flag',
            field=models.BooleanField(default=False, editable=False, verbose_name='删除'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='update_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
