# Generated by Django 2.2.2 on 2019-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190617_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
