# Generated by Django 2.2.2 on 2019-06-19 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('del_flag', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('current_currency', models.CharField(max_length=10, verbose_name='当前币种')),
                ('target_currency', models.CharField(max_length=10, verbose_name='目标币种')),
                ('multiplying_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='转换率')),
                ('currency_date', models.DateField(verbose_name='汇率日期')),
                ('create_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('update_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '汇率管理',
                'verbose_name_plural': '汇率管理',
            },
        ),
    ]
