# Generated by Django 2.2.2 on 2019-06-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('del_flag', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('code', models.CharField(max_length=100, verbose_name='费用代码')),
                ('name', models.CharField(max_length=300, verbose_name='费用名称')),
                ('create_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('update_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
