# Generated by Django 2.2.2 on 2019-06-17 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('del_flag', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('order_num', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='主单号')),
                ('create_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('update_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('del_flag', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('order_num', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='分单号')),
                ('create_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('update_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('del_flag', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('arrival_date', models.DateField(verbose_name='到货日期')),
                ('order_num', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='订单号')),
                ('pre_carton', models.IntegerField(verbose_name='预计件数')),
                ('pre_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预计重量')),
                ('pre_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预计体积')),
                ('pre_size', models.CharField(blank=True, max_length=500, null=True, verbose_name='预报尺寸')),
                ('carton', models.IntegerField(verbose_name='件数')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='体积')),
                ('charge_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计费重量')),
                ('size', models.CharField(blank=True, max_length=500, null=True, verbose_name='尺寸')),
                ('airline', models.CharField(max_length=20, verbose_name='航空公司')),
                ('airline_date', models.DateField(verbose_name='航班日期')),
                ('create_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Customer', verbose_name='客户')),
                ('house_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.HouseOrder', verbose_name='分单号')),
                ('master_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.MasterOrder', verbose_name='主单号')),
                ('update_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
