# Generated by Django 2.2.2 on 2019-06-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'verbose_name': '客户订单', 'verbose_name_plural': '客户订单'},
        ),
        migrations.AlterModelOptions(
            name='houseorder',
            options={'verbose_name': '分单', 'verbose_name_plural': '分单'},
        ),
        migrations.AlterModelOptions(
            name='masterorder',
            options={'verbose_name': '主单', 'verbose_name_plural': '主单'},
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='houseorder',
            name='order_num',
            field=models.CharField(max_length=30, null=True, verbose_name='分单号'),
        ),
        migrations.AlterField(
            model_name='masterorder',
            name='order_num',
            field=models.CharField(max_length=30, null=True, verbose_name='主单号'),
        ),
    ]
