# Generated by Django 2.2.2 on 2019-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190619_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='charge_trans',
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=10, null=True, verbose_name='计费转换'),
        ),
    ]
