# Generated by Django 2.2.2 on 2019-06-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_customerordercharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordercharge',
            name='currency_type',
            field=models.CharField(choices=[('CNY', 'CNY'), ('USD', 'USD'), ('GBK', 'GBK'), ('EUR', 'EUR')], default='CNY', max_length=10, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_status',
            field=models.CharField(choices=[('DR', '草稿'), ('SM', '已提交'), ('WO', '等待作业'), ('FC', '完成'), ('VO', '作废')], default='SM', max_length=30, null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='customerordercharge',
            name='charge_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='info.Charge', verbose_name='费用名称'),
        ),
        migrations.AlterField(
            model_name='customerordercharge',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Supplier', verbose_name='供应商'),
        ),
    ]
